name: pull-request-workflow
on: 
  pull_request:
    types: [opened] # 지정하지 않으면 opened, synchronize, reopened시 동작


jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action