name: var-1
on: push

# 전체 workspace에 대한 env는 github에서 설정
env:
  level: workflow

jobs:
  get-env-1:
    runs-on: ubuntu-latest
    steps:
    - name: check env
      run: echo "LEVEL ${{ env.level }}"

  get-env-2:
    runs-on: ubuntu-latest
    env:
      level: step2
    steps:
    - name: check env
      run: echo "LEVEL ${{ env.level }}"

  get-env-3:
    runs-on: ubuntu-latest
    env:
      level: step3
    steps:
    - name: check env
      runs: echo "LEVEL ${{ env.level }}"

  get-env:
    runs-on: ubuntu-latest
    steps:
    - name: create env
      run: echo "level=job" >> $GITHUB_ENV  
    - name: check env
      run: echo "LEVEL ${{ env.level }}"