name: environment
on: push

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
    - name: check env & secret
      run: | # vars는env, secrets 는 secret 설정
        echo ${{ vars.level }}
        echo ${{ secrets.key }}

  get-env-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: check env & secret
      run: |
        echo ${{ vars.level }}
        echo ${{ secrets.key }}