name: tag-filter
on:
  push:
    tages: # git tag v0.0.0
    - 'v[0-9]+.[0-9]+.[0-9]+'  # v1.1.0 등 형식에 반응


jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello