name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "job1 done"

  job2:
    runs-on: ubuntu-latest
    needs: [job1] 
    steps:
    - name: echo
      run: echo "job2 done after job1"
  
  job3:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "job3 failed"
        exit 1 #job 강제실패

  job4:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "job4 done" #실행안됨
